WatchStore/Areas/Admin/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WatchStore.Models;

namespace WatchStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly WatchStoreContext _context;

        public UsersController(WatchStoreContext context)
        {
            _context = context;
        }

        // GET: Admin/Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        // GET: Admin/Users/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: Admin/Users/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Users/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,UserName,Phone,Email,Password,Role,IsAdmin")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Admin/Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Admin/Users/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserId,UserName,Phone,Email,Password,Role,IsAdmin")] User user)
        {
            if (id != user.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Admin/Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Admin/Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.FindAsync(id);
            if (user != null)
            {
                _context.Users.Remove(user);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.UserId == id);
        }
    }
}

WatchStore/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WatchStore.Models;
using WatchStore.Repository;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System.Security.Claims;
namespace WatchStore.Controllers
{
   
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly IBrandRepository _brandRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ProductController(IProductRepository productRepository, IBrandRepository brandRepository, IHttpContextAccessor httpContextAccessor)
        {
            _productRepository = productRepository;
            _brandRepository = brandRepository;
            _httpContextAccessor = httpContextAccessor;
        }
        private ApplicationDbContext db = new ApplicationDbContext();
        private const string connectionString = "LAPTOP-POTNR7PE\\SQLEXPRESS";

        public async Task<IActionResult> Index()
        {
            var products = await _productRepository.GetAllAsync();
            
            return View(products);
        }


        public IActionResult Search(string searchTerm, string sortOrder ,int products)
        {
            // Gọi phương thức tìm kiếm từ repository
            IEnumerable<Product> searchResults = _productRepository.SearchWatch(searchTerm);

            // Trả về view với kết quả tìm kiếm
            return View("SearchResults", searchResults);
        }
        private int GetUserId()
        {
            if (_httpContextAccessor.HttpContext.User.Identity is ClaimsIdentity identity && identity.IsAuthenticated)
            {

                var userIdClaim = identity.FindFirst(ClaimTypes.NameIdentifier);

                if (userIdClaim != null && int.TryParse(userIdClaim.Value, out int userId))
                {
                    return userId;
                }
            }

            return 0;
        }
        public async Task<IActionResult> Like(int productId)
        {
            var product = await _productRepository.GetByIdAsync(productId);
            if (product != null)
            {
                // Xác định người dùng hiện tại
                var userId = GetUserId();
                if (userId != 0)
                {
                    // Kiểm tra xem người dùng đã thích sản phẩm này chưa
                    bool isLiked = await _productRepository.IsProductLikedByUser(productId, userId);
                    if (!isLiked)
                    {
                        // Nếu chưa thích, thêm vào bảng LikedProducts
                        await _productRepository.AddProductLike(productId, userId);
                    }
                    else
                    {
                        // Nếu đã thích, có thể xử lý việc hủy thích sản phẩm ở đây
                        // await _productRepository.RemoveProductLike(productId, userId);
                    }
                }
            }
            return RedirectToAction(nameof(Index)); // Chuyển hướng trở lại trang chính
        }

        public async Task<IActionResult> LikedProducts()
        {
            // Xác định người dùng hiện tại
            var userId = GetUserId();
            if (userId != 0)
            {
                var likedProducts = await _productRepository.GetLikedProductsByUserIdAsync(userId);
                return View(likedProducts);
            }
            return RedirectToAction("Login", "Home"); // Chuyển hướng nếu người dùng chưa đăng nhập
        }

        //Show add new book page
        public async Task<IActionResult> Add()
        {
            var brands = await _brandRepository.GetAllAsync();
            ViewBag.Brand = new SelectList(brands, "Id", "Name");
            return View();

        }
        [HttpPost]
        public async Task<IActionResult> Add(Product product)
        {
            if (ModelState.IsValid)
            {
                await _productRepository.AddAsync(product);
                return RedirectToAction("Index");
            }
            var brands = await _brandRepository.GetAllAsync();
            ViewBag.Brand = new SelectList(brands, "Id", "Name");
            return View(product);

        }

        //Show detail of a book
        public async Task<ActionResult> Detail(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        //Show update page of the book
        public async Task<IActionResult> Update(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            var brands = await _brandRepository.GetAllAsync();
            ViewBag.Brands = new SelectList(brands, "Id", "Name", product);
            return View(product);

        }

        public async Task<IActionResult> SortByName()
        {
            var sortedProducts = await _productRepository.GetAllAsync();
            sortedProducts = sortedProducts.OrderBy(p => p.Name);
            return View("Index", sortedProducts);
        }

        public async Task<IActionResult> SortByPriceAsc()
        {
            var sortedProducts = await _productRepository.GetAllAsync();
            sortedProducts = sortedProducts.OrderBy(p => p.Price);
            return View("Index", sortedProducts);
        }
        public async Task<IActionResult> SortByPriceDesc()
        {
            var sortedProducts = await _productRepository.GetAllAsync();
            sortedProducts = sortedProducts.OrderByDescending(p => p.Price);
            return View("Index", sortedProducts);
        }

        //Process the book update
        [HttpPost]
        public async Task<IActionResult> Update(int id, Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                await _productRepository.UpdateAsync(product);
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        //Show the book delete confirmation
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _productRepository.GetByIdAsync(id);
            if (product == null)
                return NotFound();
            return View(product);
        }



        //Process the book deletion
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

WatchStore/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WatchStore.Models;
using WatchStore.Repository;

namespace WatchStore.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ApplicationDbContext _context;
        private readonly IUserRepository _userRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public ShoppingCartController(IProductRepository productRepository, 
            ApplicationDbContext context, IUserRepository userRepository, IHttpContextAccessor httpContextAccessor)
        {
            _productRepository = productRepository;
            _context = context;
            _userRepository = userRepository;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            // Lấy thông tin giỏ hàng từ cookie
            var cartJson = Request.Cookies["Cart"];
            var cart = cartJson != null ? JsonConvert.DeserializeObject<ShoppingCart>(cartJson) : new ShoppingCart();
            if (cart.Items.Count == 0)
            {
                return View("Empty");
            }
            return View(cart);
        }
        [HttpPost]
        public IActionResult UpdateQuantity(int productId, int quantity)
        {
            // Lấy thông tin giỏ hàng từ cookie
            var cartJson = Request.Cookies["Cart"];
            if (string.IsNullOrEmpty(cartJson))
            {
                return RedirectToAction("Index");
            }

            var cart = JsonConvert.DeserializeObject<ShoppingCart>(cartJson);
            var itemToUpdate = cart.Items.FirstOrDefault(item => item.ProductId == productId);
            if (itemToUpdate != null)
            {
                itemToUpdate.Quantity = quantity;
            }

            // Cập nhật lại cookie
            Response.Cookies.Append("Cart", JsonConvert.SerializeObject(cart));

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            var product = await GetProductFromDatabase(productId);
            if (product == null)
            {
                // Xử lý khi sản phẩm không tồn tại...
                return RedirectToAction("Index");
            }

            var cartItem = new CartItem
            {
                ProductId = product.Id,
                Name = product.Name,
                Price = product.Price,
                Quantity = quantity,
            };

            // Lấy thông tin giỏ hàng từ cookie
            var cartJson = Request.Cookies["Cart"];
            var cart = cartJson != null ? JsonConvert.DeserializeObject<ShoppingCart>(cartJson) : new ShoppingCart();

            // Thêm sản phẩm vào giỏ hàng
            cart.Items.Add(cartItem);

            // Lưu giỏ hàng vào cookie
            Response.Cookies.Append("Cart", JsonConvert.SerializeObject(cart));

            return RedirectToAction("Index");
        }

        private async Task<Product> GetProductFromDatabase(int productId)
        {
            // Truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm
            return await _productRepository.GetByIdAsync(productId);
        }
        private int GetUserId()
        {
            if (_httpContextAccessor.HttpContext.User.Identity is ClaimsIdentity identity && identity.IsAuthenticated)
            {

                var userIdClaim = identity.FindFirst(ClaimTypes.NameIdentifier);

                if (userIdClaim != null && int.TryParse(userIdClaim.Value, out int userId))
                {
                    return userId;
                }
            }

            return 0;
        }
        public async Task<IActionResult> Checkout()
        {
            return View(new Order());
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            // nhận userid hiện tại 
            int userId = GetUserId();
            // Lấy thông tin giỏ hàng từ cookie
            var cartJson = Request.Cookies["Cart"];
            var cart = cartJson != null ? JsonConvert.DeserializeObject<ShoppingCart>(cartJson) : new ShoppingCart();
            if (cart == null)
            {
                // Xử lý giỏ hàng trống...
                return RedirectToAction("Index");
            }

           
            order.UserId = userId;
            order.OrderDate = DateTime.UtcNow;
            order.TotalPrice = cart.Items.Sum(i => i.Price * i.Quantity);
            order.OrderDetails = cart.Items.Select(i => new OrderDetail
            {
                ProductId = i.ProductId,
                Quantity = i.Quantity,
                Price = i.Price
            }).ToList();


            _context.Orders.Add(order);
            await _context.SaveChangesAsync();
            HttpContext.Session.Remove("Cart");
            return View("OrderCompleted", order.Id); // Trang xác nhận hoàn thành đơn hàng
        }
        public IActionResult RemoveFromCart(int productId)
        {
            // Lấy thông tin giỏ hàng từ cookie
            var cartJson = Request.Cookies["Cart"];
            if (string.IsNullOrEmpty(cartJson)) // Kiểm tra nếu cookie không tồn tại hoặc rỗng
            {
                return View("Empty");
            }

            var cart = JsonConvert.DeserializeObject<ShoppingCart>(cartJson);

            // Xóa sản phẩm có productId khỏi giỏ hàng
            cart.Items.RemoveAll(item => item.ProductId == productId);

            // Lưu lại giỏ hàng vào cookie
            Response.Cookies.Append("Cart", JsonConvert.SerializeObject(cart));

            return RedirectToAction("Index");
        }
    }
}

WatchStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WatchStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/bootswach.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WatchStore.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="/RetailSmart/Jquery/jquery.multiselect.css" rel="stylesheet" />

    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-black border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WatchStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ShoppingCart" asp-action="Index">Cart</a>

                        </li>
                        <li class="nav-item">
                            <a asp-controller="Product" asp-action="LikedProducts" class="nav-link text-light">LikedProducts</a>
                        </li>

                    </ul>
                    </a>

                </div>
                <form class="d-flex">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            if (!User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a asp-controller="Home" asp-action="Login" class="nav-link text-light">Login</a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Home" asp-action="Register" class="nav-link text-light">Register</a>
                                </li>
                            }
                        }
                        @{
                            if (User.Identity.IsAuthenticated)
                            {
                                <li class="nav-item">
                                    <a asp-controller="Home" asp-action="Logout" class="nav-link text-light">Logout</a>
                                </li>


                            }
                        }
                        <li class="nav-item">
                            <button class="btn btn-outline-light" asp-controller="ShoppingCart" asp-action="Index" type="submit">
                                <i class="bi-cart-fill me-1"></i>
                                Cart
                            </button>
                        </li>
                    </ul>
                </form>
            </div>


            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - WatchStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WatchStore/Views/Shared/_SideNavPartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="side-nav ">
    <div class="side-nav-inner">
        <ul class="side-nav-menu scrollable">
            <li class="nav-item ">
                <a class="dropdown-toggle"   asp-controller="Admin" asp-action="Index">
                    <span class="icon-holder">
                        <i class="anticon anticon-dashboard"></i>
                    </span>
                    <span class="title ">Dashboard</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
               
            </li>
            
           
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-hdd"></i>
                    </span>
                    <span class="title" <a asp-controller="Admin" asp-action="Index">System Manager </a></span> 
                    <p class="arrow" style="top:12px">
                        <i class="arrow-icon"></i>
                    </p>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a   asp-controller="Products" asp-action="Index">Quản lý sản phẩm</a>
                    </li>
                    <li>
                        <a asp-controller="Users" asp-action="Index">Quản lý người dùng</a>
                    </li>
                    <li>
                        <a asp-controller="Orders" asp-action="Index">Lịch sử mua hàng</a>
                    </li>
                    <li>
                        <a asp-controller="Orders" asp-action="Statistics">Thống kê người mua hàng</a>
                    </li>
                  
                </ul>
            </li>
            <li><a asp-controller="Admin" asp-action="Logout" asp-area="Admin" class="nav-link">Logout</a></li>
         
        </ul>
    </div>
</div>